use sakilla;

select title, inventory_id, inventory.store_id
from film
inner join inventory
on film.film_id = inventory.film_id
inner join store
on inventory.store_id=store.store_id;


#retrieve each category names and the number of films it has

select count(title), category_id
from film_category as fc
inner join category as c
on c.category_id=fc.category_id
group by category_id;


#Retrieve the store ID, city, and country for each store.

select store_id, city, country
from store
inner join address
on store.address_id=address.address_id
inner join city
on address.city_id=city.city_id
inner join country
on city.country_id=country.country_id;

#Error Code: 1054. Unknown column 'store' in 'field list'


#Calculate the total revenue generated by each store in dollars.

select store.store_id, CONCAT('$', FORMAT(SUM(amount), 2)) AS total_revenue
from store
inner join staff
on store.store_id=staff.store_id
inner join payment
on staff.staff_id=payment.staff_id
group by store.store_id;


#Determine the average running time of films for each category

select ROUND(AVG(length), 2), name
from film
inner join film_category
on film.film_id=film_category.film_id
inner join category
on film_category.category_id=category.category_id
group by name;



#Identify the film categories with the longest average running time.

select ROUND(AVG(length), 2) as avg_length, name
from film
inner join film_category
on film.film_id=film_category.film_id
inner join category
on film_category.category_id=category.category_id
group by name
order by avg_length desc
limit 5;





